version: '3.7'

services:
  postgres:
    image: postgres:10
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=R00Tpostgres
      - POSTGRES_DB=nestjs-resfulapi-pzn
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro

  # redis:
  #   image: "redis:5.0-alpine"
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --maxclients 10000 --requirepass redis-edooba-ymb
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   depends_on:
  #     - postgres
  #     - minio

  # minio:
  #   image: "minio/minio:RELEASE.2021-06-07T21-40-51Z"
  #   ports:
  #     - 9000:9000
  #   environment:
  #     MINIO_ACCESS_KEY: minio
  #     MINIO_SECRET_KEY: minio-edooba-ymb
  #   command: server /data
  #   volumes:
  #     - minio:/data:rw
  #     - /etc/localtime:/etc/localtime:ro
  #   depends_on:
  #     - postgres

  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbit"
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
  #   labels:
  #     NAME: "rabbitmq"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   depends_on:
  #     - postgres
  #     - minio

volumes:
  pgdata:
  # minio:
